/**
  * Created by derauk on 2/13/16.
  */

object PermanentAlias {

  def main(args: Array[String]): Unit = {

    // Create the profile to be used by any of the commands
    val profile = BashProfile.create()

    if(args.length == 0) {
      this.printhelp()
      return
    }

    args(0) match {
      case "-h" => printhelp()
      case "--help" => printhelp()
      case "-l" => listAliases(profile)
      case "--list" => listAliases(profile)
      case _ => {
        if(args.length < 2) {
          this.printhelp()
          println("-- Please pass 2 arguments to the command--")
        }

        this.addCommand(profile, args)
      }
    }
  }

  def listAliases(profile: BashProfile): Unit = {
    println("List of aliases generated by perma:")
    println(s"\t${profile.aliases.mkString("\n\t")}")
  }

  def addCommand(profile: BashProfile, args: Array[String]): Unit = {
    val alias = args(0)

    val cmdBuilder = StringBuilder.newBuilder
    args.drop(1).foreach(x => cmdBuilder.append(s"$x "))
    val cmd = cmdBuilder.toString()

    try {
      profile.addAlias(alias, cmd)
      println(s"Adding $alias->$cmd as an alias to .bash_profile")
    } catch {
      case e: Exception => println(s"Error: ${e.getMessage()}")
    }

    profile.write()
  }

  def printhelp(): Unit = {
    println("perma: - add an alias permanently to your profile")
    println("usage: 'perma tst echo test' will add 'tst=echo test' to your .bash_profile")
  }

}
