/**
  * Created by derauk on 2/13/16.
  */

object PermanentAlias {

  def main(args: Array[String]): Unit = {

    if(args.length == 1 && (args(0).equals("-h") || args(0).equals("--help"))){
        printhelp()
        return
    }

    // Create the profile to be used by any of the commands
    val profile = BashProfile.create()

    if(args.length == 1 && (args(0).equals("-l") || args(0).equals("--list"))){
      println("List of aliases generated by perma:")
      println(s"\t${profile.aliases.mkString("\n\t")}")
      return
    }

    if(args.length > 1) {
      val alias = args(0)

      val cmdBuilder = StringBuilder.newBuilder
      args.drop(1).foreach(x => cmdBuilder.append(s"$x "))
      val cmd = cmdBuilder.toString()


      try {
        profile.addAlias(alias, cmd)
        println(s"Adding $alias->$cmd as an alias to .bash_profile")
      } catch {
        case e: Exception => println(s"Error: ${e.getMessage()}")
      }

      profile.write()
    } else {
      printhelp()
      println("-- Please pass 2 arguments to the command--")
    }
  }

  def printhelp(): Unit = {
    println("perma: - add an alias permanently to your profile")
    println("usage: 'perma tst echo test' will add 'tst=echo test' to your .bash_profile")
  }
}
